apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloworld
  name: helloworld
spec:
  containers:
  - image: busybox
    name: sleep
    command:
    - /bin/sh
    - -c
    - sleep 500
    ports:
    - containerPort: 80

  - image: gcr.io/google-samples/hello-app:1.0
    name: helloworld
    ports:
      - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
